# Site settings
title: Studies on Computational Linguistics II (Spring 2023)
tag_text: Studies on Computational Linguistics II (Spring 2023)
description: Spring 2023 Studies on Computational Linguistics II @ Dept. of Linguistics, Seoul National University
url: "https://sanajlee.github.io" # base URL for your site ie. "https://www.example.com"
baseurl: "/nlp2023g" # subpath for base of site, leave blank if hosting at root

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
